/**
 * The page of the book, for a citation on /history.
 *
 * /history says "Pate 1917" and asks you to take it on trust. This resolves that
 * chip into the actual leaf of the actual gazetteer — the whole printed page,
 * with the sentence we relied on sitting inside it where a reader can see what
 * came before and after.
 *
 * THE WHOLE PAGE IS THE POINT. A quotation we cropped ourselves is not evidence;
 * it is an assertion with quotation marks around it. Printing the page around it
 * is what lets a reader catch us cherry-picking — the qualifier we left out, the
 * sentence before that would have changed the meaning. It costs us the ability to
 * hide, which is exactly what a citation is supposed to cost.
 *
 * RIGHTS ARE NOT THE SAME QUESTION AS EVIDENCE. Two independent axes, and they
 * must not be confused:
 *   · `tier` (citations.ts) — how strongly the claim is evidenced.
 *   · `rights` (here)       — whether we may lawfully reproduce the page image.
 * Cronin 1959 is an excellent outside witness we may NOT scan (Vincent Cronin
 * died in 2011). The parish souvenir is ours to print and is our weakest possible
 * support. Strong evidence can be unshowable; showable evidence can be weak.
 *
 * Data is generated by scripts/build_references.py from the books on disk.
 * Hand-edits to reference-leaves.json will be overwritten.
 */

import LEAVES from "@/data/reference-leaves.json";
import { HISTORY_CITATIONS, sortKeys } from "@/lib/citations";
import { leafKey } from "@/lib/referenceIndex";
import type { Leaf } from "@/lib/referenceIndex";

export { leafKey, hasLeaf, RIGHTS_NOTE } from "@/lib/referenceIndex";
export type { Rights, LeafKind, Leaf } from "@/lib/referenceIndex";

/**
 * The books themselves. SERVER ONLY — this is ~300KB of Pate, Bertrand and Auguste Jean,
 * and it must never reach a browser. A client component that needs to know whether a leaf
 * exists imports `hasLeaf` from referenceIndex.ts instead, which is eight kilobytes of keys.
 */
const ALL = LEAVES as unknown as Record<string, Leaf>;

export const getLeaf = (era: string, dot: number, source: string): Leaf | undefined =>
  ALL[leafKey(era, dot, source)];

/** The other books this same moment rests on — strongest witness first, ours last. */
export const siblingsOf = (era: string, dot: number): string[] =>
  sortKeys(HISTORY_CITATIONS[era]?.[dot]?.keys ?? []);

/** Every leaf that exists, for generateStaticParams and for /sources. */
export const allLeafKeys = (): { era: string; dot: string; source: string }[] =>
  Object.keys(ALL).map((k) => {
    const [era, dot, source] = k.split(":");
    return { era, dot, source };
  });

/**
 * The first moment on /history that leans on a given book.
 *
 * /sources lists the book; this is how that listing offers "read the page" without
 * the bibliography having to know anything about the timeline.
 */
export const firstLeafFor = (source: string) =>
  allLeafKeys().find((k) => k.source === source);
