"use client";

import { useEffect, useRef, useState, type RefObject } from "react";

/* ── THE PHONE MEMORY BUDGET, AND WHY THIS IS NOT A PLAIN PRELOAD ──────────
   iOS Safari does not run a page out of memory the way a desktop browser
   does. It kills it: the WebContent process is jetsammed and the reader gets
   "This page couldn't load — Reload to try again", with no console, no error
   and no clue as to which page element was to blame. Chrome on Android and
   every desktop browser survive the same page, so it is invisible unless you
   are holding an iPhone.

   The hero is exactly the shape that trips it. This loader used to fetch all
   150 frames up front and hold every Image alive for the life of the page.
   Encoded that is a harmless ~16 MB — but WebKit caches the DECODED bitmap of
   each frame it draws, and a decoded 864×1080 frame is 3.6 MB. Scrub through
   the whole film and the tab is asked to hold something like 540 MB of
   bitmaps, on top of the canvas backing store and the rest of the page. Its
   decoded-image cache does purge under pressure, but not at the rate a fast
   scrub fills it, and the tab dies mid-scroll. Add the ten or fifty other
   tabs a real reader keeps open and the ceiling is lower still.

   Three rules keep it bounded, and none of them changes a pixel of what is
   actually drawn:

   1. PHONES DRAW EVERY STEP-th FRAME. The scrub maps ~120vh of scroll onto
      the film, so at 150 frames the film advances more than a frame per 7px
      of scroll — far finer than a thumb can resolve. Every third frame is
      one image per ~20px, still smooth, and a third of the memory. The
      caller's frame mapping is untouched: it keeps asking for frame 97, and
      `draw` renders the nearest one that is resident.
   2. ONLY A WINDOW AROUND THE PLAYHEAD IS RESIDENT. Frames further than KEEP
      away are dropped for the collector, so the ceiling is the window, not
      the film. On a hard flick the scrub can outrun the window; that is what
      the nearest-resident search in `draw` is for — it shows the closest
      frame it has and self-heals as the next ones land.
   3. NOTHING IS HELD WHILE THE HERO IS OFF SCREEN OR THE TAB IS HIDDEN. Once
      the reader is past the hero — i.e. for the whole rest of the home page —
      the sequence costs nothing. The canvas keeps its last bitmap, so coming
      back shows the frame you left on while the window refills behind it.

   Re-fetching an evicted frame is a disk-cache hit, not a network round trip:
   /hero-frames is served with a day of max-age (see next.config.ts), which is
   what makes eviction cheap enough to be this aggressive. */
const STEP = 3;
/** Raw-index reach of the resident window, ahead of and behind the playhead. */
const AHEAD = 14 * STEP;
const BEHIND = 4 * STEP;
/** Beyond this the Image is dropped: ±16 frames ≈ 33 live ≈ 120 MB decoded. */
const KEEP = 16 * STEP;
/** Concurrent fetches — enough to stay ahead of a scroll, polite to the page. */
const IN_FLIGHT = 6;

/**
 * Picks how a scroll-scrubbed film renders and wires the mobile path.
 *
 * Desktop (≥768px, same breakpoint as useLenis) scrubs the real <video> via
 * currentTime — smooth there, with Lenis feeding it eased wheel deltas. Touch
 * devices instead draw a pre-extracted WebP frame sequence onto a <canvas>
 * (the Apple product-page technique): every currentTime set is a full async
 * seek through the media pipeline, which stutters on phones no matter how the
 * file is encoded — and this way the multi-MB video never downloads on mobile
 * at all. Sequences are generated by scripts/gen-scrub-frames.mjs.
 *
 * The caller renders <video> only when mode === "video" and <canvas> only
 * when mode === "canvas", waits for mediaReady, then drives frames from its
 * own ScrollTrigger scrub:
 *
 *   frameTargetRef.current = frame;
 *   drawRef.current?.();
 */
export function useScrubMedia({
  videoRef,
  canvasRef,
  frameCount,
  frameSrc,
  focusX = 0.5,
}: {
  videoRef: RefObject<HTMLVideoElement | null>;
  canvasRef: RefObject<HTMLCanvasElement | null>;
  frameCount: number;
  /** Module-level constant, so the loader effect never re-runs. */
  frameSrc: (i: number) => string;
  /**
   * Horizontal focal point of the SOURCE frame, 0–1, that should land in the
   * middle of the canvas — the canvas equivalent of `object-position`, and
   * therefore mobile-only (the desktop <video> path ignores it). 0.5 is plain
   * centre-cover; above 0.5 slides the image left to bring something that
   * sits right of frame-centre into the middle. Clamped so the crop can never
   * run past an edge of the frame.
   */
  focusX?: number;
}) {
  const [mode, setMode] = useState<"video" | "canvas" | null>(null);
  const [mediaReady, setMediaReady] = useState(false);

  const frameTargetRef = useRef(0);
  const drawRef = useRef<(() => void) | null>(null);

  useEffect(() => {
    setMode(window.matchMedia("(min-width: 768px)").matches ? "video" : "canvas");
  }, []);

  // ── Desktop: wait for video metadata (duration) before wiring the scrub ──
  useEffect(() => {
    if (mode !== "video") return;
    const video = videoRef.current;
    if (!video) return;

    const onLoaded = () => setMediaReady(true);
    video.addEventListener("loadedmetadata", onLoaded);
    if (video.readyState >= 1) onLoaded();
    return () => video.removeEventListener("loadedmetadata", onLoaded);
  }, [mode, videoRef]);

  // ── Mobile: size the canvas and stream the frame sequence in ──
  useEffect(() => {
    if (mode !== "canvas") return;
    const canvas = canvasRef.current;
    const ctx = canvas?.getContext("2d");
    if (!canvas || !ctx) return;

    // Lives for exactly as long as this effect — a ref would outlive the
    // canvas it belongs to and keep its frames alive with it.
    const frames: (HTMLImageElement | null)[] = new Array(frameCount).fill(null);
    const pending = new Set<number>();
    let inFlight = 0;
    let drawn = -1;
    let cancelled = false;
    /* Is the hero on screen and the tab in front? While it is not, the film
       holds nothing — see rule 3 above. */
    let resident = true;

    /* A scroll-scrubbed film is motion like any other, so a reader who has
       asked for less of it gets the opening frame and nothing after it — which
       is the poster already underneath the canvas, so nothing shifts and they
       carry none of this memory. Read once: `mediaReady` still fires below or
       the hero's copy would never be revealed. */
    const still = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    const want = () =>
      Math.max(0, Math.min(frameCount - 1, Math.round(frameTargetRef.current)));

    const draw = () => {
      const want0 = want();
      // Nearest loaded frame, so scrubbing ahead of the network shows the
      // closest image instead of freezing (and self-heals as frames arrive).
      let idx = -1;
      for (let d = 0; d < frameCount && idx < 0; d++) {
        if (want0 - d >= 0 && frames[want0 - d]) idx = want0 - d;
        else if (want0 + d < frameCount && frames[want0 + d]) idx = want0 + d;
      }
      if (idx < 0 || idx === drawn) return;
      const img = frames[idx] as HTMLImageElement;
      // Same geometry as the video's object-cover, with focusX standing in
      // for object-position's x. Put focusX*dw under the canvas centre, then
      // clamp into [cw - dw, 0] so the frame still covers edge to edge.
      const { width: cw, height: ch } = canvas;
      const scale = Math.max(cw / img.naturalWidth, ch / img.naturalHeight);
      const dw = img.naturalWidth * scale;
      const dh = img.naturalHeight * scale;
      const dx = Math.max(Math.min(cw - dw, 0), Math.min(0, cw / 2 - focusX * dw));
      ctx.drawImage(img, dx, (ch - dh) / 2, dw, dh);
      drawn = idx;
    };

    const size = () => {
      // Render at native density (capped at 3×) — capping lower makes the
      // browser upscale the canvas element itself, which visibly softens
      // the film on flagship phones. One full-screen canvas at 3× is only
      // ~12 MB of backing store; drawImage cost is unaffected by dpr here.
      const dpr = Math.min(window.devicePixelRatio || 1, 3);
      const w = Math.round(canvas.clientWidth * dpr);
      const h = Math.round(canvas.clientHeight * dpr);
      if (canvas.width === w && canvas.height === h) return; // address-bar churn
      canvas.width = w;
      canvas.height = h;
      drawn = -1; // resizing wipes the bitmap — force a redraw
      draw();
    };
    size();
    window.addEventListener("resize", size);

    // Plain Image objects + one canvas, never ImageBitmaps: an ImageBitmap is
    // decoded the moment it exists and stays that way until it is closed, so a
    // sequence of them is the very pile of bitmaps this loader exists to
    // avoid. A frame that lands after the playhead has already moved past its
    // window is dropped on arrival rather than stored and evicted later.
    const load = (i: number) => {
      pending.add(i);
      inFlight++;
      const img = new window.Image();
      img.decoding = "async";
      const settle = () => {
        pending.delete(i);
        inFlight--;
        pump();
      };
      img.onload = () => {
        if (!cancelled && resident && Math.abs(i - want()) <= KEEP) {
          frames[i] = img;
          draw();
        }
        settle();
      };
      img.onerror = settle;
      img.src = frameSrc(i);
    };

    const request = (i: number) => {
      if (i < 0 || i >= frameCount || frames[i] || pending.has(i)) return;
      load(i);
    };

    /* Runs after every scrub tick and every time a frame lands: drop what the
       playhead has left behind, then fetch what it is about to want, nearest
       first. Requests are snapped to a FIXED grid of multiples of STEP — if the
       grid moved with the playhead, a slow scroll would fetch 30, then 31, then
       32 and hold three near-identical images where one was intended. */
    const pump = () => {
      if (cancelled || still) return;
      const at = want();
      for (let i = 0; i < frameCount; i++) {
        if (frames[i] && (!resident || Math.abs(i - at) > KEEP)) frames[i] = null;
      }
      if (!resident) return;

      const lastOnGrid = Math.floor((frameCount - 1) / STEP) * STEP;
      const base = Math.min(Math.round(at / STEP) * STEP, lastOnGrid);
      for (let d = 0; d <= AHEAD && inFlight < IN_FLIGHT; d += STEP) {
        request(base + d);
        if (d > 0 && d <= BEHIND) request(base - d);
      }
      // The grid stops short of the final frame; pin it so the film's last
      // composition is the one that actually lands at the end of the scrub.
      if (at > lastOnGrid) request(frameCount - 1);
    };

    // The consumer's every scrub tick: draw with what is here, then move the
    // window. Internal callers (a frame landing, a resize) only draw — pumping
    // from there would recurse.
    drawRef.current = () => {
      draw();
      pump();
    };

    /* Frame 0 gates the hero's entrance animations, so it is fetched on its own
       before the window opens — and setMediaReady runs even if it 404s, because
       a missing file must not leave the hero's copy invisible forever. */
    const first = new window.Image();
    first.decoding = "async";
    first.onload = () => {
      if (cancelled) return;
      frames[0] = first;
      setMediaReady(true);
      draw();
      pump();
    };
    first.onerror = () => {
      if (cancelled) return;
      setMediaReady(true);
      pump();
    };
    first.src = frameSrc(0);

    /* Residency: on screen AND in front. A viewport of slack either side of the
       hero keeps a reader lingering at the boundary from thrashing the cache;
       the visibility half matters because backgrounding a tab is exactly when
       iOS goes looking for memory to reclaim, and the tab holding less is the
       tab it is less likely to discard. */
    let onScreen = true;
    let visible = true;
    const settleResidency = () => {
      resident = onScreen && visible;
      pump();
    };

    const io = new IntersectionObserver(
      ([entry]) => {
        onScreen = entry.isIntersecting;
        settleResidency();
      },
      { rootMargin: "100% 0px" }
    );
    io.observe(canvas);

    const onVisibility = () => {
      visible = document.visibilityState === "visible";
      settleResidency();
    };
    document.addEventListener("visibilitychange", onVisibility);

    return () => {
      cancelled = true;
      drawRef.current = null;
      window.removeEventListener("resize", size);
      io.disconnect();
      document.removeEventListener("visibilitychange", onVisibility);
      // Leaving the page must not leave 33 decoded frames behind it.
      frames.fill(null);
    };
  }, [mode, frameCount, frameSrc, canvasRef, focusX]);

  return { mode, mediaReady, frameTargetRef, drawRef };
}
