"use client";

import { useEffect, useRef, useState, type RefObject } from "react";

/**
 * Picks how a scroll-scrubbed film renders and wires the mobile path.
 *
 * Desktop (≥768px, same breakpoint as useLenis) scrubs the real <video> via
 * currentTime — smooth there, with Lenis feeding it eased wheel deltas. Touch
 * devices instead draw a pre-extracted WebP frame sequence onto a <canvas>
 * (the Apple product-page technique): every currentTime set is a full async
 * seek through the media pipeline, which stutters on phones no matter how the
 * file is encoded — and this way the multi-MB video never downloads on mobile
 * at all. Sequences are generated by scripts/gen-scrub-frames.mjs.
 *
 * The caller renders <video> only when mode === "video" and <canvas> only
 * when mode === "canvas", waits for mediaReady, then drives frames from its
 * own ScrollTrigger scrub:
 *
 *   frameTargetRef.current = frame;
 *   drawRef.current?.();
 */
export function useScrubMedia({
  videoRef,
  canvasRef,
  frameCount,
  frameSrc,
}: {
  videoRef: RefObject<HTMLVideoElement | null>;
  canvasRef: RefObject<HTMLCanvasElement | null>;
  frameCount: number;
  /** Module-level constant, so the loader effect never re-runs. */
  frameSrc: (i: number) => string;
}) {
  const [mode, setMode] = useState<"video" | "canvas" | null>(null);
  const [mediaReady, setMediaReady] = useState(false);

  const framesRef = useRef<(HTMLImageElement | null)[]>([]);
  const frameTargetRef = useRef(0);
  const drawRef = useRef<(() => void) | null>(null);

  useEffect(() => {
    setMode(window.matchMedia("(min-width: 768px)").matches ? "video" : "canvas");
  }, []);

  // ── Desktop: wait for video metadata (duration) before wiring the scrub ──
  useEffect(() => {
    if (mode !== "video") return;
    const video = videoRef.current;
    if (!video) return;

    const onLoaded = () => setMediaReady(true);
    video.addEventListener("loadedmetadata", onLoaded);
    if (video.readyState >= 1) onLoaded();
    return () => video.removeEventListener("loadedmetadata", onLoaded);
  }, [mode, videoRef]);

  // ── Mobile: size the canvas and stream the frame sequence in ──
  useEffect(() => {
    if (mode !== "canvas") return;
    const canvas = canvasRef.current;
    const ctx = canvas?.getContext("2d");
    if (!canvas || !ctx) return;

    framesRef.current = new Array(frameCount).fill(null);
    let drawn = -1;
    let cancelled = false;

    const draw = () => {
      const frames = framesRef.current;
      const want = Math.round(frameTargetRef.current);
      // Nearest loaded frame, so scrubbing ahead of the network shows the
      // closest image instead of freezing (and self-heals as frames arrive).
      let idx = -1;
      for (let d = 0; d < frameCount && idx < 0; d++) {
        if (want - d >= 0 && frames[want - d]) idx = want - d;
        else if (want + d < frameCount && frames[want + d]) idx = want + d;
      }
      if (idx < 0 || idx === drawn) return;
      const img = frames[idx] as HTMLImageElement;
      // Same geometry as the video's object-cover.
      const { width: cw, height: ch } = canvas;
      const scale = Math.max(cw / img.naturalWidth, ch / img.naturalHeight);
      const dw = img.naturalWidth * scale;
      const dh = img.naturalHeight * scale;
      ctx.drawImage(img, (cw - dw) / 2, (ch - dh) / 2, dw, dh);
      drawn = idx;
    };
    drawRef.current = draw;

    const size = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      const w = Math.round(canvas.clientWidth * dpr);
      const h = Math.round(canvas.clientHeight * dpr);
      if (canvas.width === w && canvas.height === h) return; // address-bar churn
      canvas.width = w;
      canvas.height = h;
      drawn = -1; // resizing wipes the bitmap — force a redraw
      draw();
    };
    size();
    window.addEventListener("resize", size);

    // Plain Image objects + one canvas (never ImageBitmaps): the browser
    // keeps them compressed (a few MB total) and decodes on draw, which
    // stays far below iOS Safari's canvas/bitmap memory ceilings.
    const load = (i: number) =>
      new Promise<void>((done) => {
        const img = new window.Image();
        img.onload = () => {
          if (!cancelled) {
            framesRef.current[i] = img;
            draw();
          }
          done();
        };
        img.onerror = () => done();
        img.src = frameSrc(i);
      });

    (async () => {
      await load(0); // entrance animations gate on this one
      if (cancelled) return;
      setMediaReady(true);
      let next = 1;
      const pump = async () => {
        while (!cancelled && next < frameCount) await load(next++);
      };
      // Modest parallelism: fast enough to beat the first scroll, polite
      // enough not to starve the rest of the page.
      for (let k = 0; k < 6; k++) pump();
    })();

    return () => {
      cancelled = true;
      drawRef.current = null;
      window.removeEventListener("resize", size);
    };
  }, [mode, frameCount, frameSrc, canvasRef]);

  return { mode, mediaReady, frameTargetRef, drawRef };
}
